lang: yue
title: 童話王國17周年生日卡活動展覽
author: Dragon de Lune
email: lunadragon0v0@gmail.com
description: 重新展現跑者無限創意！
long_description: |
  優秀的創作者們值得一個更好的舞台。
  本站並非跑Online官方網站。與戲谷、Smilegate或RHAON等等無關。

social:
  instagram: _dragondelune
  youtube_channel: _dragondelune
  github: dragondelune

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
