lang: yue
title: 跑Online童話王國17周年生日卡活動重製版
author: Dragon de Lune
email: lunadragon0v0@gmail.com
description: >-
  跑Online充滿優秀的創作者，他們的努力值得一個更好的舞台。

social:
  instagram: _dragondelune
  youtube_channel: _dragondelune
  github: dragondelune

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
